### ISSUE TITLE
[Bug]: The Telescope find_files command changed the directory, which had previously been showing the root directory

### ISSUE THREAD

**Issue by angryheng** [ChristianChiarulli/nvcode#1851]
### Problem description

The Telescope find_files command changed the directory, which had previously been showing the root directory

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6.0

### Screenshots

![bug](https://user-images.githubusercontent.com/28853495/138842812-f41dc36c-31f3-4227-8bc2-6c0bc900291d.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by hmble** [comment]
I am also having the same issue. Earlier it worked but started seeing this issue after doing LvimUpdate. After [this commit](https://github.com/LunarVim/LunarVim/commit/177916d63d7e1c748c48436ef93b30f0019eacac)

The issue is that if we have a monerepo and we open only a subrepo with lvim and then do `find_files` then it shows all files of monorepo instead of showing files only from subrepo.

**Comment by kylo252** [comment]
> After [this commit](https://github.com/LunarVim/LunarVim/commit/177916d63d7e1c748c48436ef93b30f0019eacac)

I think you may have linked the wrong commit.

> The issue is that if we have a monerepo and we open only a subrepo with lvim and then do `find_files` then it shows all files of monorepo instead of showing files only from subrepo.

This is still related to how the CWD is getting updated. To be clear, these changes are caused by the refactoring of nvim-tree so some (old) options aren't behaving as expected. Before running `find_file` you can just check this `lua print(vim.fn.getcwd())` and then tune the CWD settings to your liking.

**Comment by hmble** [comment]
> This is still related to how the CWD is getting updated. To be clear, these changes are caused by the refactoring of nvim-tree so some (old) options aren't behaving as expected.

I can confirm this as cwd get changed after i run `find_file`. Maybe its an issue with nvim-tree.

**Comment by kola-web** [comment]
lvim.builtin.project.active = false

**Comment by hmble** [comment]
This worked for after latest update https://github.com/LunarVim/LunarVim/commit/02a1e769be9139dfe7294d24b7be2d09bb30b77f
```
lvim.builtin.nvimtree.update_cwd = true
```
