### ISSUE TITLE
Can not update the newest `nvim-lspconfig` by pressing `<space>ps`

### ISSUE THREAD

**Issue by xyecoding** [ChristianChiarulli/nvcode#4586]
### Problem description

The lsp error reports `[lspconfig] unhandled error: ...site/pack/lazy/opt/nvim-lspconfig/lua/lspconfig/util.lua:266: attempt to c
all method 'flatten' (a nil value)`. This error is already corrected in the latest version of the `nvim-lspconifg` package.  The code in the latest version of `nvim-lspconfig/lua/lspconfig/util.lua` is corrected from `local nvim_ten = vim.fn.has 'nvim-0.10' == 1
` to `local nvim_eleven = vim.fn.has 'nvim-0.11' == 1`. However, when I press `<space>ps` to  update the plugins, lunarvim can not get the latest version of `nvim-lspconfig` and the lsp error is still exists.
 

### LunarVim version

85ccca97acfea9a465e354e18bb2f6109ba417f8

### Neovim version (>= 0.9.1)

NVIM v0.10.0-dev-4258f4d

### Operating system/version

arh linux /6.9.6-arch1-1

### Affected language servers

all

### Actual behavior

Can not get the latest version of `nvim-lspconfig` when `<space>ps` is pressed.

### Expected behavior

Get the latest version of `nvim-lspconfig` when `<space>ps` is pressed.

### support info

`[lspconfig] unhandled error: ...site/pack/lazy/opt/nvim-lspconfig/lua/lspconfig/util.lua:266: attempt to c
all method 'flatten' (a nil value)` is get from LspInfo.

`Buffer info                                                                         │
~          │* filetype:                lua                                                      │
~          │* bufnr:                   1                                                        │
~          │* treesitter status:       active                                                   │
~          │                                                                                    │
~          │Active client(s)                                                                    │
~          │                                                                                    │
~          │Automatic LSP info                                                                  │
~          │* Skipped servers: [angularls, ansiblels, antlersls, ast_grep, azure_pipelines_ls, b│
~          │asedpyright, biome, bzl, css_variables, cssmodules_ls, custom_elements_ls, denols, d│
~          │ocker_compose_language_service, dprint, elp, ember, emmet_language_server, emmet_ls,│
~          │ eslint, fennel_language_server, gitlab_ci_ls, glint, glslls, golangci_lint_ls, grad│
~          │le_ls, graphql, harper_ls, hdl_` is get from LvimInfo.

**Comment by juicy-g** [comment]
This is by design. For stability, LunarVim pins plugins in a snapshot file to exactly prevent those issues even on master. Syncing the core plugins by `<leader>ps` matches those plugins versions to the snapshot file. It does not update the core plugins to the latest versions.

You should have the stable version of Neovim installed. If you want to live on the bleeding edge, then LunarVim might not be the distro for you. If you still want to do this in LunarVim, check out this part of the docs for how to unpin plugins: [https://www.lunarvim.org/docs/configuration/plugins/core-plugins#pinning](https://www.lunarvim.org/docs/configuration/plugins/core-plugins#pinning).
